### ISSUE TITLE
Shall I create an Anki deck?

### ISSUE THREAD

**Issue by teivah** [teivah/designdeck#1]
[Anki](https://apps.ankiweb.net/) is a free software (Windows/Mac/Linux/iPhone/Android) which makes remembering things easy. It utilizes spaced repetition which is a proven technique to increase the rate of memorization:  

[![](http://img.youtube.com/vi/-uMMRjrzPmE/0.jpg)](http://www.youtube.com/watch?v=-uMMRjrzPmE "Spaced Repetition: The most powerful study technique")

_Spaced Repetition: The most powerful study technique on YouTube_

> The single biggest change that Anki brings about is that it means memory is no longer a haphazard event, to be left to chance. Rather, it guarantees I will remember something, with minimal effort. That is, Anki makes memory a choice.

_Michael A. Nielsen, "Augmenting Long-term Memory"_

If you're interesting about an Anki deck, please upvote this issue using 👍.

**Comment by ahmedalnuaimi** [comment]
Yes please 🙏

**Comment by teivah** [comment]
I made available the Anki deck version: https://github.com/teivah/designdeck#anki-deck.
